### Check server status
GET http://localhost:5555/status

### Check server stats
GET http://localhost:5555/stats



### Start "Guess number" game
# - generates number to guess
# 400 - if game is already started
POST http://localhost:5555/start-game

### Guess number 1..100
# 400 - if out of range
# 400 - if not number
# returns LESS|EQUAL|BIGGER
POST http://localhost:5555/guess
Content-Type: application/json

80

### End "Guess number" game
# - forgets number to guess
# 400 - if game already ended
POST http://localhost:5555/end-game

###